apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agon-web
  namespace: latere
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - agon.latere.ai
      secretName: agon-web-tls
  rules:
    - host: agon.latere.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agon-web
                port:
                  number: 80
